# Generated by Django 4.0.6 on 2022-07-21 13:45

from django.db import migrations
from apps.blog.models import BlogCategory


def add_blog_categories(apps, schema_editor):
    categories = [
        'Нщвщсти',
        'Обзоры',
        'Акции',
        'Партнерам',
        'Спец предложения',
    ]
    for category in categories:
        BlogCategory.objects.create(name= category)

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_category'),
    ]

    operations = [
        migrations.RunPython(add_blog_categories)
    ]
