# Generated by Django 4.0.6 on 2022-07-21 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_add_blog_articles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='text_previev',
            new_name='text_preview',
        ),
    ]
