# Generated by Django 4.0.6 on 2022-08-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_teg'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tegs',
            field=models.ManyToManyField(to='blog.teg', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='image',
            field=models.ImageField(null=True, upload_to='blog/category/', verbose_name='Зображення'),
        ),
    ]
